name: Build & Release Go Binaries

on:
  push:
    tags:
      - 'v*' # Trigger only when a tag like v1.0.0 is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Build binaries
        run: |
          mkdir -p dist
          GOOS=linux   GOARCH=amd64 go build -o dist/gohide-linux-amd64   .
          GOOS=windows GOARCH=amd64 go build -o dist/gohide-windows-amd64.exe .
          GOOS=darwin  GOARCH=amd64 go build -o dist/gohide-darwin-amd64  .
          GOOS=darwin  GOARCH=arm64 go build -o dist/gohide-darwin-arm64  .

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
